import { chromium, expect } from '@playwright/test';
const baseURL = process.env.SMOKE_BASE_URL || 'http://127.0.0.1:3100';
const browser = await chromium.launch({ headless: true });
const errors = [];
const results = [];
try {
  const context = await browser.newContext({ viewport: { width: 1365, height: 900 } });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push({ url: page.url(), message: error.message }));
  const firebaseCalls = [];
  page.on('request', request => {
    if (/firestore\.googleapis\.com|identitytoolkit\.googleapis\.com|securetoken\.googleapis\.com/.test(request.url())) firebaseCalls.push(request.url());
  });
  const response = await page.goto(baseURL, { waitUntil: 'domcontentloaded' });
  expect(response?.status()).toBe(200);
  await expect(page.locator('h1').first()).toBeVisible();
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden');
  expect(await page.locator('link[href*="fonts.googleapis.com"]').count()).toBe(0);
  results.push({ page: '/', ready: true });
  const catalogRequests = [];
  page.on('request', request => { if (request.url().includes('/api/data/')) catalogRequests.push(request.url()); });
  const catalogResponse = await page.goto(baseURL + '/products', { waitUntil: 'domcontentloaded' });
  const html = await catalogResponse.text();
  expect(html).toContain('/products/');
  await expect(page.locator('a[href^="/products/"]').first()).toBeVisible();
  await page.locator('nav a[href*="category="]').first().click();
  expect(catalogRequests.length).toBe(0);
  results.push({ page: '/products', serverRendered: true, catalogApiRequests: catalogRequests.length });
  await page.goto(baseURL + '/news', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('a[href^="/news/"]').first()).toBeVisible();
  expect(firebaseCalls).toEqual([]);
  results.push({ page: '/news', ready: true, publicFirebaseRequests: firebaseCalls.length });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(baseURL + '/products', { waitUntil: 'domcontentloaded' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  results.push({ mobileCatalog: true });
  const catalog = await (await context.request.get(baseURL + '/api/data/cakes?limit=1')).json();
  const product = catalog.data[0];
  expect(product).toBeTruthy();
  const cart = [{ id: product.id, name: product.name, slug: product.slug, imageUrl: product.imageUrl, price: product.price, quantity: 1 }];
  await context.addInitScript(cart => { localStorage.setItem('vibary-cart', JSON.stringify(cart)); }, cart);
  await page.goto(baseURL + '/cart', { waitUntil: 'domcontentloaded' });
  await expect(page.getByText(product.name, { exact: true }).first()).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('vibary-cart') || '[]').length)).toBe(1);
  results.push({ cartRestored: true });
  await page.goto(baseURL + '/admin/login', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('input[type="password"]')).toBeVisible();
  await expect(page.getByLabel('Tên đăng nhập', { exact: true })).toBeVisible();
  expect(await page.locator('input[type="email"]').count()).toBe(0);
  expect((await context.request.get(baseURL + '/api/data/orders')).status()).toBe(401);
  expect(firebaseCalls).toEqual([]);
  results.push({ adminLoginVisible: true, privateApiProtected: true, firebaseRequests: firebaseCalls.length });
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ results, browserErrors: errors }, null, 2));
} finally { await browser.close(); }
